---

- name: Create data directory
  file:
    path: "{{ opendistroforelasticsearch_db_dir }}"
    state: directory
    owner: "{{ opendistroforelasticsearch_user }}"
    group: "{{ opendistroforelasticsearch_group }}"
    mode: 0750

- name: Create opendistroforelasticsearch_log_dir directory
  file:
    path: "{{ opendistroforelasticsearch_log_dir }}"
    state: directory
    owner: "{{ opendistroforelasticsearch_user }}"
    group: "{{ opendistroforelasticsearch_group }}"
    mode: 0755

- name: Create path.scripts directory if specified
  # XXX this should have been created by package
  file:
    path: "{{ opendistroforelasticsearch_scripts_dir }}"
    state: directory
  when:
    - opendistroforelasticsearch_scripts_dir | length > 0

- name: Create opendistroforelasticsearch_conf_dir
  file:
    path: "{{ opendistroforelasticsearch_conf_dir }}"
    mode: 0755
    owner: "{{ opendistroforelasticsearch_user }}"
    group: "{{ opendistroforelasticsearch_group }}"
    state: directory

- name: Create elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: "{{ opendistroforelasticsearch_conf_file }}"
    mode: 0440
    owner: "{{ opendistroforelasticsearch_user }}"
    group: "{{ opendistroforelasticsearch_group }}"
  notify:
    - Restart opendistroforelasticsearch
