---

- name: Install elasticsearch
  pkgng:
    name: "{{ opendistroforelasticsearch_package }}"
    state: present

- name: Create rc.subr flagment
  template:
    src: FreeBSD.rc.j2
    dest: /etc/rc.conf.d/opendistroforelasticsearch
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart opendistroforelasticsearch
