---
# tasks file for ansible-role-elasticsearch

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: "Include configure.yml"
  include: configure.yml

- name: "Include configure-jvm-{{ ansible_os_family }}.yml"
  include: "configure-jvm-{{ ansible_os_family }}.yml"

- name: "Include plugins.yml"
  include: plugins.yml

- name: Start opendistroforelasticsearch
  service:
    name: "{{ opendistroforelasticsearch_service }}"
    state: started
    enabled: yes
  register: register_elasticsearch_start

- name: Wait for elasticsearch to start in task
  wait_for:
    host: localhost
    port: "{{ opendistroforelasticsearch_http_port }}"
  when:
    - register_elasticsearch_start.changed
